eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: kownlege-graph-database-server
  data:
    neo4j:
      username: neo4j
      password: 123456
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080